# Model configuration
model_name: 'dmis-lab/biobert-v1.1'  # BioBERT pre-trained on biomedical literature

# Training parameters
seed: 42
batch_size: 2
learning_rate: 2e-5
num_epochs: 2
warmup_steps: 0.1
max_length: 512
validation_split: 0.1   # Percentage of training data to use for validation

# Data paths
train_data_path: '../BioASQ-training13b/training13b.json'
word2vec_model_path: './data/word2vecTools'

# Output paths
data_set_output_path: './output/dataset.json'
output_dir: './output/'
